# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livredor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_signature',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
