# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livredor', '0002_message_message_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_signature',
            new_name='signature',
        ),
    ]
