# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livredor', '0003_auto_20180528_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='signature',
            field=models.CharField(max_length=50),
        ),
    ]
