# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livredor', '0004_auto_20180528_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='message',
            name='message_title',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100),
        ),
    ]
