# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livredor', '0006_message_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_title',
            field=models.CharField(max_length=100),
        ),
    ]
