# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livredor', '0007_auto_20180529_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='pub_date',
        ),
    ]
